name: Deploy Site on Github Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Hugo Site with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src hugomods/hugo hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
